import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
//properties([pipelineTriggers([githubPush()])])
pipeline {
  agent any
  environment {
    appName = "variable" 
  }
  tools {nodejs "NodeJSInstaller"}
  stages {


stage("Build"){
     
      steps {
        dir('proyectosa') {
          sh 'ls'
          sh "pwd"
          sh "npm install"
        }
          
      }
    }
stage("Test"){
     
      steps {
          dir('proyectosa') {
          sh 'ls'
          sh "pwd"
          sh "npm run testci --watch=false"
        }
      }
    }
stage("Deploy"){
     
      steps {
          dir('proyectosa') {
          sh "npm start"
        }
      }
    }
  }
  post {
      always {        
           sh "echo 'fase always'"
      }
      success {
            sh "echo 'fase success'"
        }

      failure {
            sh "echo 'fase failure'"
      }
      
  }
}  