import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
//properties([pipelineTriggers([githubPush()])])
pipeline {
  agent any
  environment {
    appName = "variable" 
  }
  tools {nodejs "NodeJSInstaller"}
  stages {


stage("Build"){
     
      steps {
        dir('proyectosa') {
          sh "RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \ && echo \"deb http://dl.google.com/linux/chrome/deb/ stable main\""
          sh "RUN apt-get update && apt-get -y install google-chrome-stable ."
          sh 'ls'
          sh "pwd"
          sh "rm -rf node_modules"
          sh "rm package-lock.json" 
          sh "npm cache clear --force"
          sh "npm install"
        }
          
      }
    }
stage("Test"){
     
      steps {
          dir('proyectosa') {
          sh 'ls'
          sh "pwd"
          sh "npm run testci --watch=false"
        }
      }
    }
  }
  post {
      always {          
          deleteDir()
           sh "echo 'fase always'"
      }
      success {
            sh "echo 'fase success'"
        }

      failure {
            sh "echo 'fase failure'"
      }
      
  }
}  