import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}
//properties([pipelineTriggers([githubPush()])])
pipeline {
  agent any
  environment {
    appName = "variable" 
  }
  tools {nodejs "NodeJSInstaller"}
  stages {

 stage("paso 1"){
     
      steps {
          script {			
           sh "echo 'Se realizo un push en master'"
        }
      }
    }
stage("comprobacion npm"){
     
      steps {
          script {		
            sh 'node -v'
            sh "npm --version"
        }
      }
    }
stage("Build"){
     
      steps {
          script {		
           sh "cd proyectosa"
           sh "npm install"
        }
      }
    }
stage("Test"){
     
      steps {
          script {			
           sh "npm test"
        }
      }
    }
  }
  post {
      always {          
          deleteDir()
           sh "echo 'fase always'"
      }
      success {
            sh "echo 'fase success'"
        }

      failure {
            sh "echo 'fase failure'"
      }
      
  }
}  